FROM balenalib/raspberry-pi:buster-20200221

ENV UPDATED=20200225
ENV REDIS_HOST=redis
RUN apt update \ 
    && apt install python3 python3-pip \
    && apt install python3-smbus libraspberrypi-bin \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install gpiozero asyncio redis starlette uvicorn aiofiles itsdangerous jinja2 aioredis